export interface Theme {
  id: string;
  name: string;
  category: "dark" | "light" | "vibrant" | "retro";
  bgColor: string;
  mainColor: string;
  caretColor: string;
  subColor: string;
  subAltColor: string;
  textColor: string;
  errorColor: string;
  errorExtraColor: string;
}

export const THEMES: Theme[] = [
  {
    id: "serika_dark",
    name: "Serika Dark",
    category: "dark",
    bgColor: "#323437",
    mainColor: "#e2b714",
    caretColor: "#e2b714",
    subColor: "#646669",
    subAltColor: "#2c2e31",
    textColor: "#d1d0c5",
    errorColor: "#ca4754",
    errorExtraColor: "#7e2a33",
  },
  {
    id: "serika",
    name: "Serika Light",
    category: "light",
    bgColor: "#e1e1e3",
    mainColor: "#d1a307",
    caretColor: "#d1a307",
    subColor: "#92989f",
    subAltColor: "#d1d3d8",
    textColor: "#323437",
    errorColor: "#da3333",
    errorExtraColor: "#791717",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    category: "vibrant",
    bgColor: "#10141b",
    mainColor: "#00ffcc",
    caretColor: "#00ffcc",
    subColor: "#324050",
    subAltColor: "#171d26",
    textColor: "#e0f8ff",
    errorColor: "#ff0055",
    errorExtraColor: "#a30036",
  },
  {
    id: "dracula",
    name: "Dracula",
    category: "dark",
    bgColor: "#282a36",
    mainColor: "#bd93f9",
    caretColor: "#f1fa8c",
    subColor: "#6272a4",
    subAltColor: "#21222c",
    textColor: "#f8f8f2",
    errorColor: "#ff5555",
    errorExtraColor: "#ff79c6",
  },
  {
    id: "nord",
    name: "Nord",
    category: "dark",
    bgColor: "#2e3440",
    mainColor: "#88c0d0",
    caretColor: "#88c0d0",
    subColor: "#4c566a",
    subAltColor: "#3b4252",
    textColor: "#d8dee9",
    errorColor: "#bf616a",
    errorExtraColor: "#8b3c43",
  },
  {
    id: "carbon",
    name: "Carbon",
    category: "dark",
    bgColor: "#313131",
    mainColor: "#f66e0d",
    caretColor: "#f66e0d",
    subColor: "#616161",
    subAltColor: "#272727",
    textColor: "#f5e6c8",
    errorColor: "#e43636",
    errorExtraColor: "#8a1f1f",
  },
  {
    id: "botanical",
    name: "Botanical",
    category: "dark",
    bgColor: "#202a28",
    mainColor: "#7b9c98",
    caretColor: "#9ec4be",
    subColor: "#495e5b",
    subAltColor: "#18201f",
    textColor: "#eaf1f1",
    errorColor: "#e25b5b",
    errorExtraColor: "#8a2424",
  },
  {
    id: "chalk",
    name: "Chalk",
    category: "dark",
    bgColor: "#282c34",
    mainColor: "#61afef",
    caretColor: "#61afef",
    subColor: "#5c6370",
    subAltColor: "#21252b",
    textColor: "#abb2bf",
    errorColor: "#e06c75",
    errorExtraColor: "#be5046",
  },
  {
    id: "8008",
    name: "8008",
    category: "dark",
    bgColor: "#333a45",
    mainColor: "#f44c7f",
    caretColor: "#f44c7f",
    subColor: "#939eae",
    subAltColor: "#2b313b",
    textColor: "#e9ecf0",
    errorColor: "#ff3333",
    errorExtraColor: "#990000",
  },
  {
    id: "gruvbox_dark",
    name: "Gruvbox Dark",
    category: "retro",
    bgColor: "#282828",
    mainColor: "#fabd2f",
    caretColor: "#fabd2f",
    subColor: "#7c6f64",
    subAltColor: "#1d2021",
    textColor: "#ebdbb2",
    errorColor: "#fb4934",
    errorExtraColor: "#cc241d",
  },
  {
    id: "olivia",
    name: "Olivia",
    category: "dark",
    bgColor: "#1c1b1d",
    mainColor: "#deaf9d",
    caretColor: "#deaf9d",
    subColor: "#4a474c",
    subAltColor: "#242226",
    textColor: "#f2efed",
    errorColor: "#bf616a",
    errorExtraColor: "#883e44",
  },
  {
    id: "synthwave",
    name: "Synthwave",
    category: "vibrant",
    bgColor: "#261935",
    mainColor: "#ff7edb",
    caretColor: "#36f9f6",
    subColor: "#675287",
    subAltColor: "#1e132b",
    textColor: "#fede5d",
    errorColor: "#fe4450",
    errorExtraColor: "#a82029",
  },
  {
    id: "matrix",
    name: "Matrix",
    category: "retro",
    bgColor: "#0d1117",
    mainColor: "#00ff41",
    caretColor: "#00ff41",
    subColor: "#215e29",
    subAltColor: "#07190d",
    textColor: "#00dd33",
    errorColor: "#ff0033",
    errorExtraColor: "#880011",
  },
  {
    id: "bento",
    name: "Bento",
    category: "dark",
    bgColor: "#2d394d",
    mainColor: "#ff7a90",
    caretColor: "#4d82b8",
    subColor: "#4a5b78",
    subAltColor: "#212a39",
    textColor: "#fffaf8",
    errorColor: "#ee2a4b",
    errorExtraColor: "#a0102a",
  },
  {
    id: "taro",
    name: "Taro",
    category: "dark",
    bgColor: "#130f1a",
    mainColor: "#b388eb",
    caretColor: "#b388eb",
    subColor: "#4b3e6b",
    subAltColor: "#1f182b",
    textColor: "#f1e9f9",
    errorColor: "#ff5c77",
    errorExtraColor: "#a62b40",
  },
  {
    id: "minimal_light",
    name: "Minimal Light",
    category: "light",
    bgColor: "#f8f9fa",
    mainColor: "#2563eb",
    caretColor: "#1d4ed8",
    subColor: "#94a3b8",
    subAltColor: "#e2e8f0",
    textColor: "#1e293b",
    errorColor: "#ef4444",
    errorExtraColor: "#991b1b",
  },
];

export const DEFAULT_THEME = THEMES[0];

export function getThemeById(id: string): Theme {
  return THEMES.find((t) => t.id === id) || DEFAULT_THEME;
}
